name: 01 Repo

on:
  push:
    paths:
      - 'rhods-operator/bundle/**' 
      - 'rhods-operator/Dockerfiles/bundle.Dockerfile'
    branches:
      - 'rhoai-*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to sync'
        required: true
        type: string
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as needed

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rhods-operator repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/rhods-operator
          token: ${{ secrets.BUNDLE_SYNC_TOKEN }}
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Checkout RHOAI-Build-Config repo
        uses: actions/checkout@v3
        with:
          repository: DevOps-automation-tasks/RHOAI-Build-Config
          token: ${{ secrets.BUNDLE_SYNC_TOKEN }}
          path: rbc_repo
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Sync bundle to RBC repo
        run: |
          mkdir -p rbc_repo/bundle/
          cp -r bundle/* rbc_repo/bundle/
          cp Dockerfiles/bundle.Dockerfile rbc_repo/bundle/Dockerfile

      - name: Update local branch and commit changes
        run: |
          cd rbc_repo
          git fetch origin
          git checkout ${{ github.event.inputs.branch || github.ref }}
          git pull origin ${{ github.event.inputs.branch || github.ref }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync bundle changes from rhods-operator repo" || echo "No changes to commit"

      - name: Push changes to RBC repo
        run: |
          cd rbc_repo
          git push origin ${{ github.event.inputs.branch || github.ref }}
